name: "Build PDF"
on:
  pull_request:
  push:
jobs:
  project-description-pdf:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - name: Nix Quick Install
      uses: nixbuild/nix-quick-install-action@v16
      with:
        nix_conf: |
          experimental-features = nix-command flakes
    - run: nix build . --show-trace -L --out-link result
    - run: cp result/project-description.pdf ./
    - uses: actions/upload-artifact@v3
      with:
        name: project-description
        path: ./project-description.pdf
